version: "3"
services: 
    app:
        container_name: adapter-app
        build: .
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - 'postgres'
            - 'mongo'
        links:
            - mongo
    postgres:
        container_name: postgres
        image: postgres:13.3
        ports: 
            - "5432:5432"
        volumes: 
            - pgdata:/var/lib/postgresql/data
    mongo:
        container_name: mongo
        image: mongo
        volumes: 
            - mongo-db:/data/db
        ports: 
            - "27017:27017"
volumes:
    mongo-db:
    pgdata: